/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package balic.nb.mr.bank.details;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        // classUnderTest = new Library();
       // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
